#server:
#  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/ # 앞에 붙여주는 경로
      suffix: .jsp # 뒤에 붙여주는 경로
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://song-blog-database:3307/jpa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: song
    password: 1234
    hikari:
      initialization-fail-timeout: 0
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true


  jackson:
    serialization:
      fail-on-empty-beans: false

song:
  key: song1234