server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
song:
  key: song1234
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: "jdbc:mysql://localhost:3307/jpa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    username: song
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp